<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0942" ignored="0" name="testing" tests="61" failures="11" timestamp="2019-12-26T18:02:42 MSK" time="0.101" errors="0">
  <testcase name="checkCircl" time="0.007" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircl" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircl" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircumference" time="0.002" classname="Tests.TestFigures.CircleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [20000.0] but found [1.0E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [20000.0] but found [1.0E8]
at Tests.TestFigures.RectangleTest.checkSquare(RectangleTest.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [5.0] but found [6.25]">
      <![CDATA[java.lang.AssertionError: did not expect to find [5.0] but found [6.25]
at Tests.TestFigures.RectangleTest.checkSquare(RectangleTest.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [25000.0] but found [1.0E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [25000.0] but found [1.0E8]
at Tests.TestFigures.RectangleTest.checkSquare(RectangleTest.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkQuadrat" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.CircleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.CircleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [19.635] but found [19.636]">
      <![CDATA[java.lang.AssertionError: did not expect to find [19.635] but found [19.636]
at Tests.TestFigures.CircleTest.checkSquare(CircleTest.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.CircleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [3.14159265359E8] but found [3.1415926536E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [3.14159265359E8] but found [3.1415926536E8]
at Tests.TestFigures.CircleTest.checkSquare(CircleTest.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:63)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:63)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:63)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.003" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquareEX -->
  <testcase name="checkSquareEX" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.001" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquareEX -->
  <testcase name="checkSquareEX" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquareEX" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkSquareEX(double, double)[pri:3, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class Tests.TestFigures.NotQuadratException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquareEX -->
</testsuite> <!-- testing -->
